name: portfolio CICD

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Create docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        push true
